### PR TITLE
Switched cache implementation to PSR-6

### PR DESCRIPTION
**Pull request by magnusnordlander**
Referencing #130, here is my implementation for PSR-6 compatible caching as well as resolving #48.

Let me know about any feedback. I expect we'll be rolling this out into production shortly internally, so it should soon be production tested :)

### CODE REVIEW

**Comment by bretterer** [comment]
@magnusnordlander What versions of PHP did you test this against?  I am getting errors while working on getting this merged in.

```
1) PasswordRefreshGrantTest::it_responds_to_password_grant_types
Undefined property: stdClass::$href

/Users/bretterer/Sites/com.stormpath.php.sdk/src/DataStore/DefaultDataStore.php:298
/Users/bretterer/Sites/com.stormpath.php.sdk/src/DataStore/DefaultDataStore.php:150
/Users/bretterer/Sites/com.stormpath.php.sdk/src/Oauth/PasswordGrantAuthenticator.php:47
/Users/bretterer/Sites/com.stormpath.php.sdk/tests/Oauth/PasswordRefreshGrantTest.php:64
```

**Comment by magnusnordlander** [comment]
I'm not sure if it was PHP 5.6.16 or PHP 7.0.0, but likely the latter. I'd be happy to take a look at if I can reproduce this either during the weekend or on Tuesday and Wednesday (depending on when I have the time).

**Comment by magnusnordlander** [comment]
Wow. That's incredibly odd. I'm getting this error too now, which is weird, because I'm like 90% sure the test suite passed when last I checked. Weirder still, nothing I have done should have affected this test, and I can't see how this test has *ever* passed. I'll take a look at it though. I'll be in the IRC channel for the next few hours, if you have the opportunity to, feel free to check in.

**Comment by magnusnordlander** [comment]
Okay, so I've now fixed (most of?) the test suite. I am still getting failures for SAML, but those *should* be because my account is just a Developer account. I am also getting an error for ID Site JWT tokens, and I *think* that is for the same reason.

As we discussed I now tag every object with every referenced object, and I clear the entire cache when any directory is being deleted. Sadly my IRC log is gone, so I can't check if there were any other multi-level cascades that we need to handle. Does any other come to your mind?

Would you mind trying running the suite on your CI system?

**Comment by bretterer** [comment]
Hey @magnusnordlander 

One last error on your end I believe.  I am getting an error in a test `testWillInvalidateExpands` on line 149.  Should this be an assertFalse instead of assertTrue.  isHit() returns false currently on that line.

**Comment by magnusnordlander** [comment]
You're quite correct. That assertion is now obsolete and incorrect, so I have removed it.

**Comment by bretterer** [comment]
Thank you for the great work @magnusnordlander.

We have now merged this into our dev branch ready for our next release.

**Pull request merged**
