### PR TITLE
PSR-4 Compliance

### LINKED ISSUE #17: PSR-0 has been deprecated.  All of the PHP SDK is psr-0 and needs to be changed over to PSR-4.

### PR DESCRIPTION
**Pull request by potherca**
- Moves all of the files in the `src` and `tests` directories to their respective roots for PSR-4 compliance.
- Makes the tests use the composer `autoload-dev` section.
- Fixes #17

### CODE REVIEW

**Comment by bretterer** [comment]
@potherca,  Thank you so much for the Pull Request but it seems there is a little bit of an issue.  Could you please pull in the current dev branch into your pull request and submit again so we can fully take a look at it.

**Comment by potherca** [comment]
Yeah sure, no problem.

**Comment by potherca** [comment]
Just a short note to let you know I haven't forgotten. Priorities have shifted but I will come back to this when I find the time, which might be as late as December, sadly.

**Comment by bretterer** [comment]
Thank you @potherca , I am going to close this pull request for now.  If you get to a point that you can work on this again before we make these changes internally, feel free to re-open it or create  a new PR.

**Pull request closed without merging**
