### PR TITLE
Suggested composer dependency upgrade both for JWT and Guzzle lib

### PR DESCRIPTION
**Pull request by Guibod**
Same pull request but on DEV branch.

### CODE REVIEW

**Comment by Guibod** [comment]
How do you pass the 
"InvalidArgumentException: The 'STORMPATH_SDK_TEST_API_KEY_FILE_LOCATION' environment variable needs to be set before running the tests."
in travis automatic build ?

**Comment by bretterer** [comment]
@Guibod You are currently unable to pass the API Key information during a pull request.  I am looking at ways to get this resolved but will make sure I run tests on your Pull Request soon and get it merged if everything is looking ok.  Thank you for your PR!  We always appreciate these.

**Comment by bretterer** [comment]
@Guibod Thank you for your pull request.  I had to downgrade from your suggested 3.0.0 to 2.2.0 due to an issue with the JWT library.  I have merged your changes.

**Comment by Guibod** [comment]
Ok nice. Thanks guys.

**Pull request merged**
